### ISSUE TITLE
UserStore.setUserCredentials

### ISSUE THREAD

**Issue by nachbarshund** [mpneuried/tcs_node_auth#1]
In der `UserStore.setUserCredentials` wäre es schön, wenn man mitbekommt ob der User seinen Account aktiviert oder nur sein neues Passwort setzen will. Stehen diese Informationen hier zur Verfügung? 

Denn sonst muss ich zuerst in der Datenbank schauen, ob es einen User mit dieser Email Adresse gibt und dann entscheiden, ob ich ein Update oder Insert ausführe.

**Comment by mpneuried** [comment]
**Achtung Breaking Change**
In Version `0.3.0` habe ich `UserStore.setUserCredentials` ein weiteres Boolean Argument `isRegister` hinzugefügt.
